### ISSUE TITLE
Calls

### ISSUE THREAD

**Issue by BBQGodfather** [BTNGaming/gcphone_esxfix#2]
Do you have something other than this script to make calls work? Maybe im just tired but cant get it working. it calls just nothing happens on the other side.

**Comment by JEStudios** [comment]
same

**Comment by BTNGaming** [comment]
In order to get the calls to work currently, You have to use esx_voice, or AT THE VERY LEAST, Have it running. It doesn't have to be used, But it does need to be running. (I'm going to be doing a complete rewrite of this full system in time.)
