### ISSUE TITLE
Everything works except phone calls

### ISSUE THREAD

**Issue by jozefntou** [BTNGaming/gcphone_esxfix#5]
Hi, we tried this on our test server, we have an issue with phone calls.. I can't hear him and he can't hear me.

We made sure to have esx voice but still it's not working for us

**Comment by EGUltraTM** [comment]
You need to install the voice service on a linux server. It doesnt work without it. Please look on the original github from N3MTV

**Comment by BTNGaming** [comment]
> You need to install the voice service on a linux server. It doesnt work without it. Please look on the original github from N3MTV

I run mine on a Windows server, So that information isn't 100% correct. Though it does help. But with RTP disabled, it should still work with esx_voice and normal calls.
