### ISSUE TITLE
no messages text field 

### ISSUE THREAD

**Issue by kevintransp** [BTNGaming/gcphone_esxfix#6]
Nice resourses and i would love te get it up and running. But i have a problem. When i want to sent a message to police, ambulance or mechanic nothing happens, no screen opens where i can type my message in.

**Comment by EGUltraTM** [comment]
you need also the gcphone_addons running. Look at the N3MTV github linked in the readme

**Comment by BTNGaming** [comment]
> you need also the gcphone_addons running. Look at the N3MTV github linked in the readme

Thanks for helping out with that EGUltraTM. Appreciate the quick input. :)
